name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-macOS-x64:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@master

      - name: Install Deps
        run: brew install luajit --HEAD

      - name: Build
        run: |
          make -j${nproc}

      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with: 
          name: MonaServer-macOS-x64
          path: MonaServer
          
    # TODO: Unit Tests don't work on mac for some reason    
      - name: Unit Tests
        run: |
          ./UnitTests -m=all
          cat UnitTests.log/0.log
        working-directory: UnitTests/
