name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-macOS-x64:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@master

      - name: Install Deps
        run: brew install luajit --HEAD

      - name: Build
        run: |
          make -j${nproc}
          mkdir -p MonaBin/MonaBase/lib && mkdir -p MonaBin/MonaCore/lib
          cp MonaBase/lib/*.dylib MonaBin/MonaBase/lib
          cp MonaCore/lib/*.dylib MonaBin/MonaCore/lib
          cp -r MonaServer MonaBin

      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with: 
          name: MonaServer-macOS-x64
          path: MonaBin
          
    # TODO: Unit Tests don't work on mac for some reason    
      # - name: Unit Tests
      #  run: |
      #    ./UnitTests -m=all
      #    cat UnitTests.log/0.log
      #  working-directory: UnitTests/


  build-windows:
      runs-on: windows-latest

      steps:
        - uses: actions/checkout@master
        
        - name: Setup VSC
          uses: TheMrMilchmann/setup-msvc-dev@v3
          with:
            arch: x64

        - name: Build
          run: |
            msbuild Mona.sln
            cp MonaServer/debug/* MonaServer
            rm -R MonaServer/Debug

        - name: Upload Artifact 
          uses: actions/upload-artifact@v4
          with: 
            name: MonaServer-Win
            path: MonaServer

        - name: Unit Tests
          run: |
            cp debug\* .
            .\UnitTests.exe -m=all
            cat UnitTests.log/0.log
          working-directory: UnitTests/

          
  build-linux:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@master

          - name: Install Deps
            run: |
              git clone https://github.com/LuaJIT/LuaJIT.git
              cd LuaJIT
              make -j${nproc} && sudo make install

          - name: Build
            run: |
              make -j${nproc}
              mkdir -p MonaBin/MonaServer/lib
              cp MonaBase/lib/*.so MonaBin/MonaServer/lib
              cp MonaCore/lib/*.so MonaBin/MonaServer/lib
              cp -r MonaServer MonaBin

          - name: Upload Artifact 
            uses: actions/upload-artifact@v4
            with: 
              name: MonaServer-Linux
              path: MonaBin

          - name: Unit Tests
            run: |
              ./UnitTests -m=all
              cat UnitTests.log/0.log
            working-directory: UnitTests/
